Fix(connection problems with Jira) / Core(add docker)
DataDog/gello pull request #130
Opened 2022-02-10 14:24 UTC by tdimnet

### What does this PR do?

- Fixing the connection issues we have, especially with Jira. The Jira API, which is used by the Jira library, needs the email address and password instead of the username.
- Adding docker and docker-compose (to make dev easier)
- Updating of env variables (something was wrong during onboarding and I was redirected to infinity).
- Updating of the doc.

### Motivation

### Additional Notes

- I tested both with Jira and Trello several times: I created a new email, a new Trello and Jira account and a new Github account.
- I also destroyed and recreated the environment several times. I haven't seen any other problems (but a few warnings from SqlAlchemy).

### Next Steps
- Improving logging (there are many `print` statements in the code, we should use logging).
- Removing pyenv from the project. I haven't delete the files related to pyenv yet but I think it might be interesting to stay with pip and docker instead of pyenv.
- Removing dependencies: we should remove libraries like `Flask-Moment`, `Flask-Script` and use standard/maintained instead.
- Updating dependencies.
- Refactoring some sections of the code. The code uses for example AbstractClass, this is good but it can sometimes overcomplicate the code. I should also add error messages, especially for delayed actions, like retrieving projects and Jira members.
- Turning the project into an UI App :0

2022-02-10 14:26 UTC, tdimnet commented on run.py
> +    app.run(host="0.0.0.0")
I don't think it will failed with Heroku but I am not 100% sure.

2022-02-10 14:27 UTC, tdimnet commented on app/api_clients/jira_api_client.py
> +        username = environ.get('ADMIN_EMAIL')
I don't think it will break, but since the dev/prod environments are different, I hope not :/

2022-02-10 16:32 UTC, burningion commented on docker-compose.yml
> +      POSTGRES_PASSWORD: my_password
In general, I try not to put environment variable values in github. Let's just leave these as environment variables (eliminate the colon and value here), and make a note in the docs for how to update your ~/.bashrc so you have dev environment variables set.

2022-02-10 16:55 UTC, ofek requested changes
💯

2022-02-10 16:55 UTC, ofek commented on Dockerfile
> +FROM python:3.6-slim-buster
3.6 is now EOL

```suggestion
FROM python:3.7-slim-buster
```

2022-02-10 16:55 UTC, ofek commented on docker-compose.yml
> +      POSTGRES_PASSWORD: my_password
The current approach would be much easier for us Windows users, so let's do both:

```suggestion
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-my_password}
```

2022-02-10 16:55 UTC, ofek commented on docs/development.md
> +### Miscalenous
```suggestion
### Miscellaneous
```

2022-02-11 15:12 UTC, tdimnet commented on docker-compose.yml
> +      POSTGRES_PASSWORD: my_password
Updated the doc and the .env-sample file

2022-02-15 14:08 UTC, merged